version: '3'

services:
  backend:
    build: 
      context: ./BackEnd
      dockerfile: Dockerfile
    container_name: backendMSPR
    restart: always
    ports:
      - "3001:3001"
    env_file:
      - ./BackEnd/.env

  authservice:
    build: 
      context: ./Authentification
      dockerfile: Dockerfile
    container_name: AuthService
    restart: always
    ports:
      - "3000:3000"            
    env_file:
      - ./Authentification/.env

  messagerieservice:
    build:
      context: ./Messagerie
      dockerfile: Dockerfile
    container_name: MessagerieService
    restart: always
    ports:
      - "3002:3000"            
    env_file:
      - ./Messagerie/.env

  postgres:
    image: postgres
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: arosaje
    volumes:
      - ./data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin