version: '3'

services:
  backEnd:
    build: 
      context: ./BackEnd
      dockerfile: Dockerfile
    container_name: backendMSPR
    restart: always
    ports:
      - "3001:3001"
    env_file:
      - ./BackEnd/.env

  authService:
    build: 
      context: ./Authentification
      dockerfile: Dockerfile
    container_name: AuthService
    restart: always
    ports:
      - "3000:3000"            
    env_file:
      - ./Authentification/.env

  postgres:
    image: postgres
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: mydatabase
    volumes:
      - ./data:/var/lib/postgresql/data
