name: Actions pour plusieurs projets

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  build:
    if: github.event.pull_request.merged == true || github.event_name == 'push'
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: test
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: admin
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    strategy:
      matrix:
        project:
          - BackEnd
          - Authentification
          - Messagerie
          # Ajoutez d'autres projets ici si nécessaire

    steps:
    - name: Checkout du code
      uses: actions/checkout@v2
      
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Wait for PostgreSQL
      run: |
        until pg_isready -h localhost -p 5432; do
          sleep 1
        done

    - name: Install dependencies
      run: |
        for project in ${{ matrix.project }}; do
          cd $project
          npm install
          cd ..
        done

    - name: Setup database
      run: |
        psql -h localhost -U admin -d test -f ./Docs/ScriptSQL.sql
      env:
        PGPASSWORD: admin

    - name: Run tests
      run: |
        for project in ${{ matrix.project }}; do
          cd $project
          npm test
          cd ..
        done
