name: Actions pour plusieurs projets

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        project:
          - BackEnd
          - Authentification
          - Messagerie
          # Ajoutez d'autres projets ici si nécessaire

    steps:
    - name: Checkout du code
      uses: actions/checkout@v2
      
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    
    - name: Install dependencies and run tests
      run: |
        for project in ${{ matrix.project }}; do
          cd $project
          npm install
          npm test
          cd ..
        done